# To find available Node images, see https://microsoft.com/en-us/product/devcontainers/javascript-node

# [Choice] Node.js version
ARG VARIANT="dev-22-bullseye"
FROM mcr.microsoft.com/devcontainers/javascript-node:${VARIANT}
